version: "3"
services:
  dms-buildings-sync-service-name:
    build:
      context: .
      dockerfile: ./dockerfile
    image: "geoworks/dms-buildings-sync:latest"
    container_name: dms-buildings-sync-container
    volumes:
      - /mnt/geoworks/dms-gisogd-gems-sync:/home/deql-ms/volume
    restart: always
    labels:
      org.label-schema.group: "mapcam"
    environment:
      host: 192.168.22.186
      port: 5010
      redis_host: 192.168.22.186
      redis_port: 32768
      gis_login: ""
      gis_password: ''
      gis_host: 192.168.22.186
      gis_port: '8888'
      gis_layerSyncPeriod: '60000'
      gis_layerId: ''
      buildings_mainLink: 'https://api.shichuvashia.ekspa.io/GZHI/webresources/geocap/get'
    env_file:
      - ./.env
    logging:
      options:
        max-size: 1m
    network_mode: host
